def get_default_config():
    return dict(
        Autoencoder=dict(
            arch1=[159, 128],
            arch2=[1306, 128],
            activations1='relu',
            activations2='relu',
            batchnorm=False,
        ),
        training=dict(
            epoch=500,
            lambda1=0.001,  # 1
            lambda2=0.001,  # 0.01
        ),
        cd=dict(
            region_num=836,
            category_num=162,
            lr=0.01,
            poi_f_path='dataset/cd/poi_f.npy',
            poi_info_path="dataset/cd/poi_list.pickle",
            poi_simi_path="dataset/cd/poi_simi_fined_del.npy",
            source_simi_path="dataset/cd/source_matrix_simi.npy",
            destina_simi_path="dataset/cd/destina_matrix_simi.npy",
            poi_most_sim_path="dataset/cd/poi_most_similar_list.pkl",
            source_most_sim_path="dataset/cd/source_most_similar_list.pkl",
            destina_most_sim_path="dataset/cd/destina_most_similar_list.pkl",
            source_path='dataset/cd/source_matrix_norm.npy',
            destina_path='dataset/cd/destina_matrix_norm.npy',
            co2_sum_path='dataset/cd/co2_sum.npy',
            gdp_sum_path='dataset/cd/gdp_sum.npy',
            population_sum_path='dataset/cd/population_sum.npy',
        ),
        xa=dict(
            region_num=660,
            category_num=154,
            lr=0.001,
            poi_f_path='dataset/xa/poi_f.npy',
            poi_info_path="dataset/xa/poi_list.pickle",
            poi_simi_path="dataset/xa/poi_simi_fined_del.npy",
            source_simi_path="dataset/xa/source_matrix_simi.npy",
            destina_simi_path="dataset/xa/destina_matrix_simi.npy",
            poi_most_sim_path="dataset/xa/poi_most_similar_list.pkl",
            source_most_sim_path="dataset/xa/source_most_similar_list.pkl",
            destina_most_sim_path="dataset/xa/destina_most_similar_list.pkl",
            source_path='dataset/xa/source_matrix_norm.npy',
            destina_path='dataset/xa/destina_matrix_norm.npy',
            co2_sum_path='dataset/xa/co2_sum.npy',
            gdp_sum_path='dataset/xa/gdp_sum.npy',
            population_sum_path='dataset/xa/population_sum.npy',
        ),
        bj=dict(
            region_num=594,
            category_num=159,
            lr=0.001,
            poi_f_path='dataset/bj/poi_f.npy',
            poi_info_path="dataset/bj/poi_list.pickle",
            poi_simi_path="dataset/bj/poi_simi.npy",
            source_simi_path="dataset/bj/source_matrix_simi.npy",
            destina_simi_path="dataset/bj/destina_matrix_simi.npy",
            poi_most_sim_path="dataset/bj/poi_most_similar_list.pkl",
            source_most_sim_path="dataset/bj/source_most_similar_list.pkl",
            destina_most_sim_path="dataset/bj/destina_most_similar_list.pkl",
            source_path='dataset/bj/source_matrix_norm.npy',
            destina_path='dataset/bj/destina_matrix_norm.npy',
            co2_sum_path='dataset/bj/co2_sum.npy',
            gdp_sum_path='dataset/bj/gdp_sum.npy',
            population_sum_path='dataset/bj/population_sum.npy',
        ),
        mh=dict(
            region_num=270,
        ),
    )

